\ Port of raylib examples/textures/textures_raw_data.c

800 CONSTANT screenWidth
450 CONSTANT screenHeight

CREATE fudesumiRaw 32 ALLOT
CREATE fudesumi 32 ALLOT
CREATE checkedIm 32 ALLOT
CREATE checked 32 ALLOT

960 CONSTANT chkW
480 CONSTANT chkH

: example
   screenWidth screenHeight z" raylib [textures] example - raw data" InitWindow
   fudesumiRaw z" /home/dave/Code/raylib/examples/textures/resources/fudesumi.raw"
      384 512 PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 0 LoadImageRaw drop
   fudesumi fudesumiRaw LoadTextureFromImage drop
   fudesumiRaw UnloadImage
   chkW chkH * 4 * MemAlloc  ( pixels )
   chkH 0 do
      chkW 0 do
         i 32 / j 32 / + 2 mod 0= if ORANGE else GOLD then
         over j chkW * i + 4 * + l!
      loop
   loop
   dup checkedIm !                     \ image_data
   chkW checkedIm image_width l!
   chkH checkedIm image_height l!
   1 checkedIm image_mipmaps l!
   PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 checkedIm image_format l!
   checked checkedIm LoadTextureFromImage drop
   checkedIm UnloadImage               \ also frees pixels
   60 SetTargetFPS
   begin
      BeginDrawing
         RAYWHITE ClearBackground
         checked screenWidth 2/ checked texture_width l@ 2/ -
                 screenHeight 2/ checked texture_height l@ 2/ -
                 WHITE 0.5e Fade DrawTexture
         fudesumi 430 -30 WHITE DrawTexture
         z" CHECKED TEXTURE " 84 85 30 BROWN DrawText
         z" GENERATED by CODE" 72 148 30 BROWN DrawText
         z" and RAW IMAGE LOADING" 46 210 30 BROWN DrawText
         z" (c) Fudesumi sprite by Eiden Marsal" 310 screenHeight 20 - 10 BROWN DrawText
      EndDrawing
   WindowShouldClose until
   fudesumi UnloadTexture
   checked UnloadTexture
   CloseWindow ;

example-end
